Homework 5
================
Zoey Zhao
11/19/2021

``` r
library(tidyverse)
```

## Problem 1

For this problem, we are interested in the data released by *The
Washington Post* in homicides in 50 large U.S. cities. The code chunk
below imports and cleans the data.

``` r
homicide_data <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv", na = c("", "Unknown"))%>%
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "Unsolved",
      disposition == "Open/No arrest" ~ "Unsolved",
      disposition == "Closed by arrest" ~ "Solved"
    ))%>%
  relocate(city_state)%>%
  filter(city_state != "TulsaAL")
```

Let’s focus on Baltimore, MD.

``` r
baltimore_df <-
  homicide_data%>%
  filter(city_state == "BaltimoreMD")

baltimore_summary <-
  baltimore_df%>%
  summarize(
    unsolved = sum(resolution == "Unsolved"),
    n = n())

baltimore_test <-
  prop.test(
  x = baltimore_summary%>%pull(unsolved),
  n = baltimore_summary%>%pull(n)
)

baltimore_test%>%
  broom::tidy()
```

    ## # A tibble: 1 × 8
    ##   estimate statistic  p.value parameter conf.low conf.high method    alternative
    ##      <dbl>     <dbl>    <dbl>     <int>    <dbl>     <dbl> <chr>     <chr>      
    ## 1    0.646      239. 6.46e-54         1    0.628     0.663 1-sample… two.sided

There are 64.6% of homicides in Baltimore are not solved, with a 95% CI
62.8%-66.3%.

Let’s try to iterate across the cities. 1. Write a function

``` r
prop_test_function <- function(city_df) {
  city_summary <-
  city_df%>%
  summarize(
    unsolved = sum(resolution == "Unsolved"),
    n = n()
    )
  city_test <-
  prop.test(
  x = city_summary%>%pull(unsolved),
  n = city_summary%>%pull(n)
  )
  
  return(city_test)
}
```

2.  Iterate across all cities

``` r
nested_df <-
  homicide_data%>%
  nest(data = uid:resolution)%>%
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  )%>%
  select(city_state, tidy_results)%>%
  unnest(tidy_results)%>%
  select(city_state, estimate, starts_with("conf"))

nested_df
```

    ## # A tibble: 50 × 4
    ##    city_state    estimate conf.low conf.high
    ##    <chr>            <dbl>    <dbl>     <dbl>
    ##  1 AlbuquerqueNM    0.386    0.337     0.438
    ##  2 AtlantaGA        0.383    0.353     0.415
    ##  3 BaltimoreMD      0.646    0.628     0.663
    ##  4 Baton RougeLA    0.462    0.414     0.511
    ##  5 BirminghamAL     0.434    0.399     0.469
    ##  6 BostonMA         0.505    0.465     0.545
    ##  7 BuffaloNY        0.612    0.569     0.654
    ##  8 CharlotteNC      0.300    0.266     0.336
    ##  9 ChicagoIL        0.736    0.724     0.747
    ## 10 CincinnatiOH     0.445    0.408     0.483
    ## # … with 40 more rows

Create a plot that shows the estimates and CIs for each city, and
organize cities according to the proportion of unsolved homicides.

``` r
nested_df%>%
  mutate(city_state = fct_reorder(city_state, estimate))%>%
  ggplot(aes(x = city_state, y = estimate))+
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(title = "Proportion of Unsolved Homicides with CIs",
       x = "Cities", 
       y = "Proportion of unsolved homicides")
```

![](p8105_hw5_zz2899_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->
